#!/usr/bin/env bash
# Write gluetun's control-server auth file from the key in .env.gluetun.
#
#   ./deploy/casaos/init-gluetun-auth.sh                      # server path
#   ./deploy/casaos/init-gluetun-auth.sh ~/srv-rehearsal/AppData/gluetun
#
# gluetun requires auth on the control server by default and does NOT expand
# environment variables inside this file, so the key has to be written in
# literally. That is why this is a script and not a tracked config file — the
# laptop and the server hold different keys, and neither belongs in git.
#
# Re-running is safe and idempotent: it rewrites the file from the current key.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DATA_DIR="${1:-/mnt/data/AppData/gluetun}"
ENV_FILE="$REPO_DIR/.env.gluetun"

[ -f "$ENV_FILE" ] || { echo "missing $ENV_FILE — copy .env.gluetun.example first" >&2; exit 1; }

# Read the key without sourcing the file, so a stray line can't execute.
API_KEY="$(grep -E '^GLUETUN_API_KEY=' "$ENV_FILE" | head -1 | cut -d= -f2-)"
[ -n "$API_KEY" ] || { echo "GLUETUN_API_KEY is empty in $ENV_FILE" >&2; exit 1; }

mkdir -p "$DATA_DIR/auth"
cat > "$DATA_DIR/auth/config.toml" <<EOF
# Generated by deploy/casaos/init-gluetun-auth.sh — do not edit by hand.
# Least privilege: torrent_agent only ever reads these three routes.
[[roles]]
name = "torrent-agent"
routes = ["GET /v1/vpn/status", "GET /v1/publicip/ip", "GET /v1/portforward"]
auth = "apikey"
apikey = "$API_KEY"
EOF
chmod 600 "$DATA_DIR/auth/config.toml"

echo "wrote $DATA_DIR/auth/config.toml (role: torrent-agent, auth: apikey)"
